### ISSUE TITLE
console.h has compiler warnings

### ISSUE THREAD

**Issue by sytelus** [strawlab/ros_comm#1]
console.h doesn't compile if you turn on warnings as errors. I'm getting following warnings:

```
/opt/ros/indigo/include/ros/console.h:342:176: warning: format ‘%d’ expects argument of type ‘int’, but argument 8 has type ‘std::vector<dji_sdk::MissionWaypoint_<std::allocator<void> >, std::allocator<dji_sdk::MissionWaypoint_<std::allocator<void> > > >::size_type {aka long unsigned int}’ [-Wformat=]
     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)

```

**Comment by astraw** [comment]
I can't imagine this repo has made it into any official ROS build instructions. Are you building this repo for Indigo? Why?

I think you should test on the latest repository upstream and report any still existing bugs there.

**Comment by sytelus** [comment]
Oops. Sorry! I've filed the issue in main repo:

https://github.com/ros/ros_comm/issues/810

**Comment by astraw** [comment]
No worries. Closing this.
