### ISSUE TITLE
'while' loop creates new folder for every time interval between start time and current time

### ISSUE THREAD

**Issue by SamuelHerring** [strawlab/ros_comm#4]
ros_comm/tools/rosbag/src/recorder.cpp has a bug that makes it vulnerable to generating lots of empty bag files if there is a time jump between "start_time_" and "t"(current time).

We are running recorder.cpp on a Jetson Nano, which takes some time after boot to get the up-to-date time.
This updates the system time, creating a time jump. This can easily be 100s of days, causing the recorder.cpp node to generate 100Ks of empty bag files.

The culprit is the Recorder::checkDuration function (line 389), which slowly counts forwards from the start time to the present time in 30-second (in our case) increments, creating a bag file for each.

I'd suggest that changing the line "start_time_ += options_.max_duration;" (line 401) to be "start_time_ = t;"
This would mean that this loop is only executed once on startup, and then the "start_time_" would get updated to the current time in one go, rather than in increments of "options_.max_duration".

As this would only execute once, I also suggest that the "while" (line 397) is replaced with a simple "if".

Many Thanks

**Comment by astraw** [comment]
Are you really running code directly from this repository? I suspect it is more likely you are using the original ROS distribution but ended up in this repository by accident?

(This repository should be archived.)

**Comment by SamuelHerring** [comment]
Ah yes you're absolutely right, we are using the original ROS distro.
By the looks of it, this bug hasn't been fixed on the up-to-date ROS repo either, so I will re-post on there.

Thanks for your fast response
